In [1]:
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils

Using TensorFlow backend.


In [3]:
iris = sns.load_dataset('iris')

In [4]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
iris.shape

(150, 5)

In [6]:
X = iris.values[:, :4]

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.values[:, 4]

In [9]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [10]:
train_X, test_X, train_y, test_y = train_test_split(X, y, train_size=0.5, test_size=0.5, random_state=0)

In [11]:
train_X

array([[4.6, 3.1, 1.5, 0.2],
       [5.9, 3.0, 5.1, 1.8],
       [5.1, 2.5, 3.0, 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [4.8, 3.0, 1.4, 0.1],
       [7.1, 3.0, 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3.0, 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2.0],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.2, 3.4, 5.4, 2.3],
       [4.9, 3.0, 1.4, 0.2],
       [5.7, 2.5, 5.0, 2.0],
       [6.9, 3.1, 5.4, 2.1],
       [4.4, 3.2, 1.3, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [7.2, 3.0, 5.8, 1.6],
       [5.1, 3.5, 1.4, 0.3],
       [4.4, 3.0, 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 2.3, 4.0, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [7.6, 3.0, 6.6, 2.1],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3

In [12]:
train_y

array(['setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'virginica',
       'virginica', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'setosa', 'versicolor', 'virginica', 'virginica', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'setosa', 'virginica',
       'versicolor', 'virginica

In [13]:
def one_hot_encoder(array):
    unique_values, indices = np.unique(array, return_inverse=True)
    
    print('Unique values: ', unique_values)
    print('indices: ', indices)
    
    one_hot_encoded_data = np_utils.to_categorical(indices, len(unique_values))
    return one_hot_encoded_data

In [14]:
ohe_train_y = one_hot_encoder(train_y)

Unique values:  ['setosa' 'versicolor' 'virginica']
indices:  [0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0 0
 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1 1 1 0 0 0 2 1 2
 0]


In [15]:
ohe_test_y = one_hot_encoder(test_y)

Unique values:  ['setosa' 'versicolor' 'virginica']
indices:  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1]


In [16]:
ohe_test_y

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [17]:
model = Sequential()

In [18]:
model.add(Dense(16, input_shape=(4,), name='Input_layer', activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


In [19]:
model.add(Dense(3, name='Output_Layer', activation='softmax'))

In [20]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_layer (Dense)          (None, 16)                80        
_________________________________________________________________
Output_Layer (Dense)         (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [26]:
model.fit(train_X, ohe_train_y, epochs=100, batch_size=2, verbose=1)

Epoch 1/100
75/75 [==============================] - 0s 493us/step - loss: 0.3423 - acc: 0.8400
Epoch 2/100
75/75 [==============================] - 0s 413us/step - loss: 0.3656 - acc: 0.8267
Epoch 3/100
75/75 [==============================] - 0s 360us/step - loss: 0.3276 - acc: 0.8400
Epoch 4/100
75/75 [==============================] - 0s 333us/step - loss: 0.3633 - acc: 0.7867
Epoch 5/100
75/75 [==============================] - 0s 333us/step - loss: 0.3230 - acc: 0.8400
Epoch 6/100
75/75 [==============================] - 0s 360us/step - loss: 0.2752 - acc: 0.9067
Epoch 7/100
75/75 [==============================] - 0s 333us/step - loss: 0.3103 - acc: 0.8400
Epoch 8/100
75/75 [==============================] - 0s 360us/step - loss: 0.2827 - acc: 0.9067
Epoch 9/100
75/75 [==============================] - 0s 347us/step - loss: 0.2371 - acc: 0.9333
Epoch 10/100
75/75 [==============================] - 0s 347us/step - loss: 0.2572 - acc: 0.9333
Epoch 11/100
75/75 [===================

75/75 [==============================] - 0s 373us/step - loss: 0.0821 - acc: 0.9867
Epoch 86/100
75/75 [==============================] - 0s 373us/step - loss: 0.1110 - acc: 0.9467
Epoch 87/100
75/75 [==============================] - 0s 347us/step - loss: 0.1259 - acc: 0.9467
Epoch 88/100
75/75 [==============================] - 0s 333us/step - loss: 0.1082 - acc: 0.9600
Epoch 89/100
75/75 [==============================] - 0s 333us/step - loss: 0.0952 - acc: 0.9467
Epoch 90/100
75/75 [==============================] - 0s 333us/step - loss: 0.2102 - acc: 0.9467
Epoch 91/100
75/75 [==============================] - 0s 333us/step - loss: 0.0700 - acc: 0.9867
Epoch 92/100
75/75 [==============================] - 0s 333us/step - loss: 0.1278 - acc: 0.9467
Epoch 93/100
75/75 [==============================] - 0s 333us/step - loss: 0.0936 - acc: 0.9733
Epoch 94/100
75/75 [==============================] - 0s 347us/step - loss: 0.1324 - acc: 0.9200
Epoch 95/100
75/75 [=======================

In [27]:
loss, accuracy = model.evaluate(test_X, ohe_test_y, verbose=0)

In [28]:
print('Loss = {:.2f}'.format(loss))

Loss = 0.14


In [29]:
print('Accuracy = {:.2f}'.format(accuracy))

Accuracy = 0.92


In [30]:
model_json = model.to_json()

In [31]:
with open('iris_model.json', 'w') as json_file:
    json_file.write(model_json)

In [32]:
model.save_weights('iris_model.h5')
print('saved model to disk')

saved model to disk
